// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjuIsBpvobLpK53Rrr9lUCtuB07tM7moI',
    appId: '1:1037068539625:web:60e33da03825ec6b11c278',
    messagingSenderId: '1037068539625',
    projectId: 'myfullproject-30051',
    authDomain: 'myfullproject-30051.firebaseapp.com',
    storageBucket: 'myfullproject-30051.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMd9jRc4MCO-_QSofg-2dGQYXVnaZEpuw',
    appId: '1:1037068539625:android:8c302ae87632077c11c278',
    messagingSenderId: '1037068539625',
    projectId: 'myfullproject-30051',
    storageBucket: 'myfullproject-30051.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkToop4R9kHS187hpjZrl2Go3xmppmDlk',
    appId: '1:1037068539625:ios:ee6f2b506fe5c73d11c278',
    messagingSenderId: '1037068539625',
    projectId: 'myfullproject-30051',
    storageBucket: 'myfullproject-30051.firebasestorage.app',
    iosBundleId: 'com.example.crudsimpleapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkToop4R9kHS187hpjZrl2Go3xmppmDlk',
    appId: '1:1037068539625:ios:ee6f2b506fe5c73d11c278',
    messagingSenderId: '1037068539625',
    projectId: 'myfullproject-30051',
    storageBucket: 'myfullproject-30051.firebasestorage.app',
    iosBundleId: 'com.example.crudsimpleapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjuIsBpvobLpK53Rrr9lUCtuB07tM7moI',
    appId: '1:1037068539625:web:bd0a037ecefdc3d311c278',
    messagingSenderId: '1037068539625',
    projectId: 'myfullproject-30051',
    authDomain: 'myfullproject-30051.firebaseapp.com',
    storageBucket: 'myfullproject-30051.firebasestorage.app',
  );
}
